name: Publish gem to rubygems.org (test)

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: sue445/workflows/.github/workflows/release_gem.yml@main
    with:
      repo-name: sue445/kiriban_getter
      gem-name:  kiriban_getter
    # permissions:
    #   contents: write
    #   id-token: write
