name: Publish gem to rubygems.org

on:
  workflow_dispatch:

jobs:
  release:
    uses: sue445/workflows/.github/workflows/release_gem.yml@main
    with:
      repo_name: sue445/kiriban_getter
      gem_name:  kiriban_getter
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      id-token: write
